name: Build and Deploy FastAPI to Google Cloud Kubernetes

on:
  push:
    branches: [ main ]

env:
  GKE_PROJECT: double-rigging-415508
  GKE_CLUSTER: fastapi-cluster-sample
  GKE_ZONE: europe-west3
  DEPLOYMENT_NAME: api-deployment
  IMAGE: fastapi-sample
  REGISTRY: docker.io/ryabuily/fastapi-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }} \
        -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:latest

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
    
    - name: Get the GKE credentials
      run: |
        gcloud container clusters get-credentials "${{ env.GKE_CLUSTER }}" --zone "${{ env.GKE_ZONE }}"

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.REGISTRY }}:${{ github.sha }}
